"""Router assembly for core workflow routes"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/routes/core/init.ipynb.

# %% auto #0
__all__ = ['init_core_routers']

# %% ../../../nbs/routes/core/init.ipynb #c3d4e5f6
from typing import List, Dict, Callable, Tuple

from cjm_fasthtml_app_core.core.routing import APIRouter

from ...workflow.workflow import StructureDecompWorkflow

from .status import init_status_router
from .sources import init_sources_router
from .audio import init_audio_router

# %% ../../../nbs/routes/core/init.ipynb #e5f6a7b8
def init_core_routers(
    workflow: StructureDecompWorkflow,  # The workflow instance
    prefix: str,  # Base prefix for core routes (e.g., "/workflow/core")
) -> Tuple[List[APIRouter], Dict[str, Callable]]:  # (routers, merged_routes)
    """Initialize and return all core workflow routers.
    
    Note: Chrome switching route is now in cjm-transcript-segment-align library.
    It is initialized in routes/init.py alongside the other segment-align routes.
    """
    # Initialize focused routers
    status_router, status_routes = init_status_router(
        workflow, f"{prefix}/status"
    )
    sources_router, sources_routes = init_sources_router(
        workflow, f"{prefix}/sources"
    )
    audio_router, audio_routes = init_audio_router(
        workflow, f"{prefix}/audio"
    )

    # Merge all routes for URL access
    merged_routes = {
        **status_routes,
        **sources_routes,
        **audio_routes,
    }

    routers = [status_router, sources_router, audio_router]

    return routers, merged_routes
