"""Source data retrieval route handlers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/routes/core/sources.ipynb.

# %% auto #0
__all__ = ['init_sources_router']

# %% ../../../nbs/routes/core/sources.ipynb #c3d4e5f6
from typing import Tuple, Dict, Callable

from fasthtml.common import APIRouter

from ...workflow.workflow import StructureDecompWorkflow

# %% ../../../nbs/routes/core/sources.ipynb #e5f6a7b8
def _handle_get_sources(
    workflow: StructureDecompWorkflow,  # The workflow instance
    request,  # FastHTML request object
    provider_id: str = None,  # Optional plugin name filter
    limit: int = 50  # Maximum number of results
):  # JSON response with transcription sources
    """Get available transcription sources."""
    transcriptions = workflow.source_service.query_transcriptions(
        provider_id=provider_id,
        limit=limit
    )
    return {"transcriptions": transcriptions}

# %% ../../../nbs/routes/core/sources.ipynb #g7b8c9d0
def init_sources_router(
    workflow: StructureDecompWorkflow,  # The workflow instance
    prefix: str,  # Route prefix (e.g., "/workflow/core/sources")
) -> Tuple[APIRouter, Dict[str, Callable]]:  # (router, route_dict)
    """Initialize source data routes."""
    router = APIRouter(prefix=prefix)

    @router
    def get_sources(request, provider_id: str = None, limit: int = 50):
        """Get available transcription sources."""
        return _handle_get_sources(workflow, request, provider_id, limit)

    routes = {
        "get_sources": get_sources,
    }

    return router, routes
