"""Workflow status and lifecycle route handlers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/routes/core/status.ipynb.

# %% auto #0
__all__ = ['init_status_router']

# %% ../../../nbs/routes/core/status.ipynb #c3d4e5f6
from typing import Tuple, Dict, Callable

from fasthtml.common import APIRouter

from cjm_fasthtml_interactions.core.state_store import get_session_id

from ...workflow.workflow import StructureDecompWorkflow

# %% ../../../nbs/routes/core/status.ipynb #e5f6a7b8
async def _handle_current_status(
    workflow: StructureDecompWorkflow,  # The workflow instance
    request,  # FastHTML request object
    sess  # FastHTML session object
):  # Appropriate UI component based on current state
    """Return current workflow status - determines what to show."""
    session_id = get_session_id(sess)
    
    # Check for in-progress workflow (via server-side state store)
    workflow_state = workflow.state_store.get_state(workflow.config.workflow_id, session_id)
    current_step = workflow.state_store.get_current_step(workflow.config.workflow_id, session_id)
    
    # Restore external paths from state to SourceService (fixes persistence across restarts)
    step_states = workflow_state.get("step_states", {})
    selection_state = step_states.get("selection", {})
    external_db_paths = selection_state.get("external_db_paths", [])
    if external_db_paths:
        workflow.source_service.set_external_paths(external_db_paths)
    
    # If there's existing state, resume the workflow
    if current_step or workflow_state:
        return await workflow._stepflow_router.start(request, sess)
    
    # Start fresh
    return await workflow._stepflow_router.start(request, sess)

# %% ../../../nbs/routes/core/status.ipynb #f6a7b8c9
async def _handle_reset(
    workflow: StructureDecompWorkflow,  # The workflow instance
    request,  # FastHTML request object
    sess  # FastHTML session object
):  # StepFlow start view
    """Reset workflow and return to start, preserving external DB state."""
    session_id = get_session_id(sess)
    wf_id = workflow.config.workflow_id

    # Extract environment state to preserve across reset
    workflow_state = workflow.state_store.get_state(wf_id, session_id)
    selection_state = workflow_state.get("step_states", {}).get("selection", {})
    preserved = {
        k: selection_state[k]
        for k in ("external_db_paths", "file_browser_state", "current_browse_path")
        if k in selection_state
    }

    # Reset in-memory caches so next restore re-reads from DB
    selection_result = getattr(workflow, '_selection_result', None)
    if selection_result is not None:
        selection_result.reset_state()

    # Clear all persisted state
    workflow.state_store.clear_state(wf_id, session_id)

    # Write back preserved environment state
    if preserved:
        from cjm_transcript_source_select.routes.core import _update_step_state
        _update_step_state(workflow.state_store, wf_id, session_id, **preserved)

    return await workflow._stepflow_router.start(request, sess)

# %% ../../../nbs/routes/core/status.ipynb #h8c9d0e1
def init_status_router(
    workflow: StructureDecompWorkflow,  # The workflow instance
    prefix: str,  # Route prefix (e.g., "/workflow/core/status")
) -> Tuple[APIRouter, Dict[str, Callable]]:  # (router, route_dict)
    """Initialize status and lifecycle routes."""
    router = APIRouter(prefix=prefix)

    @router
    async def current_status(request, sess):
        """Get current workflow status."""
        return await _handle_current_status(workflow, request, sess)

    @router
    async def reset(request, sess):
        """Reset workflow to beginning."""
        return await _handle_reset(workflow, request, sess)

    routes = {
        "current_status": current_status,
        "reset": reset,
    }

    return router, routes
