"""JavaScript callback generators for Phase 2 decomposition keyboard interaction"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/step_decomposition/callbacks.ipynb.

# %% auto #0
__all__ = ['generate_decomp_callbacks_script']

# %% ../../../nbs/components/step_decomposition/callbacks.ipynb #9c3ae2f7
from cjm_fasthtml_card_stack.core.config import CardStackConfig
from cjm_fasthtml_card_stack.core.html_ids import CardStackHtmlIds
from cjm_fasthtml_card_stack.core.button_ids import CardStackButtonIds
from cjm_fasthtml_card_stack.core.models import CardStackUrls
from cjm_fasthtml_card_stack.js.core import generate_card_stack_js

# %% ../../../nbs/components/step_decomposition/callbacks.ipynb #eee98aa2
def _generate_focus_change_script(
    focus_input_id: str,  # ID of hidden input for focused segment index
) -> str:  # JavaScript code for focus change callback
    """Generate JavaScript for card focus change handling."""
    return f"""
        // Called when card focus changes (from keyboard navigation library)
        window.onCardFocusChange = function(item, index, zoneId) {{
            // Update hidden input with focused segment index
            const input = document.getElementById('{focus_input_id}');
            if (input && item) {{
                input.value = item.dataset.segmentIndex || index;
            }}
        }};
    """

# %% ../../../nbs/components/step_decomposition/callbacks.ipynb #328ed0e1
def generate_decomp_callbacks_script(
    ids:CardStackHtmlIds,  # Card stack HTML IDs
    button_ids:CardStackButtonIds,  # Card stack button IDs
    config:CardStackConfig,  # Card stack configuration
    urls:CardStackUrls,  # Card stack URL bundle
    container_id:str,  # ID of the decomp container (parent of card stack)
    focus_input_id:str,  # ID of hidden input for focused segment index
) -> any:  # Script element with all JavaScript callbacks
    """Generate JavaScript for decomposition keyboard interaction.

    Delegates card-stack-generic JS to the library and injects the
    focus change callback via extra_scripts.
    """
    decomp_scripts = (
        _generate_focus_change_script(focus_input_id),
    )

    return generate_card_stack_js(
        ids=ids,
        button_ids=button_ids,
        config=config,
        urls=urls,
        container_id=container_id,
        extra_scripts=decomp_scripts,
    )
