"""Alignment service for temporal coordination via Silero VAD plugin"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/services/alignment.ipynb.

# %% auto #0
__all__ = ['AlignmentService', 'assign_chunk_to_segment', 'unassign_chunk_from_segment', 'auto_align_sequential',
           'get_unassigned_chunks', 'get_segments_without_time']

# %% ../../nbs/services/alignment.ipynb #d5c7f7f2
from typing import List, Dict, Any, Optional
import asyncio

from cjm_plugin_system.core.manager import PluginManager

from ..core.models import VADChunk, WorkingSegment

# %% ../../nbs/services/alignment.ipynb #1f748582
class AlignmentService:
    """Service for temporal alignment via Silero VAD plugin."""
    
    def __init__(
        self,
        plugin_manager: PluginManager,  # Plugin manager for accessing VAD plugin
        plugin_name: str = "cjm-media-plugin-silero-vad"  # Name of the VAD plugin
    ):
        """Initialize the alignment service."""
        self._manager = plugin_manager
        self._plugin_name = plugin_name
    
    def is_available(self) -> bool:  # True if plugin is loaded and ready
        """Check if the VAD plugin is available."""
        return self._manager.get_plugin(self._plugin_name) is not None
    
    def ensure_loaded(
        self,
        config: Optional[Dict[str, Any]] = None  # Optional plugin configuration
    ) -> bool:  # True if successfully loaded
        """Ensure the VAD plugin is loaded."""
        if self.is_available():
            return True
        
        # Try to find and load the plugin
        meta = self._manager.get_discovered_meta(self._plugin_name)
        if meta:
            return self._manager.load_plugin(meta, config or {"threshold": 0.5})
        return False
    
    async def analyze_audio_async(
        self,
        media_path: str  # Path to audio/video file
    ) -> tuple[List[VADChunk], float]:  # (VAD chunks, total duration)
        """Analyze audio file and return VAD chunks."""
        if not self.is_available():
            raise RuntimeError(f"Plugin {self._plugin_name} not loaded")
        
        # Execute plugin
        result = await self._manager.execute_plugin_async(
            self._plugin_name,
            media_path=media_path
        )
        
        # Extract ranges and metadata
        ranges = result.get('ranges', [])
        metadata = result.get('metadata', {})
        duration = metadata.get('duration', 0.0)
        
        # Convert to VADChunk objects
        chunks = []
        for idx, r in enumerate(ranges):
            chunk = VADChunk(
                index=idx,
                start_time=r.get('start', r.get('start_time', 0.0)),
                end_time=r.get('end', r.get('end_time', 0.0))
            )
            chunks.append(chunk)
        
        return chunks, duration
    
    def analyze_audio(
        self,
        media_path: str  # Path to audio/video file
    ) -> tuple[List[VADChunk], float]:  # (VAD chunks, total duration)
        """Analyze audio file synchronously."""
        return asyncio.get_event_loop().run_until_complete(
            self.analyze_audio_async(media_path)
        )

# %% ../../nbs/services/alignment.ipynb #4db733d5
def assign_chunk_to_segment(
    segment: WorkingSegment,  # Segment to assign chunk to
    chunk: VADChunk  # VAD chunk to assign
) -> tuple[WorkingSegment, VADChunk]:  # Updated segment and chunk
    """Assign a VAD chunk to a segment, updating time boundaries."""
    # Add chunk index to segment
    if chunk.index not in segment.vad_chunk_indices:
        segment.vad_chunk_indices.append(chunk.index)
        segment.vad_chunk_indices.sort()
    
    # Update segment time boundaries
    if segment.start_time is None or chunk.start_time < segment.start_time:
        segment.start_time = chunk.start_time
    if segment.end_time is None or chunk.end_time > segment.end_time:
        segment.end_time = chunk.end_time
    
    # Mark chunk as assigned
    chunk.assigned_segment = segment.index
    
    return segment, chunk

# %% ../../nbs/services/alignment.ipynb #111ac3af
def unassign_chunk_from_segment(
    segment: WorkingSegment,  # Segment to remove chunk from
    chunk: VADChunk,  # VAD chunk to unassign
    all_chunks: List[VADChunk]  # All chunks for recalculating times
) -> tuple[WorkingSegment, VADChunk]:  # Updated segment and chunk
    """Remove a VAD chunk assignment from a segment."""
    # Remove chunk index from segment
    if chunk.index in segment.vad_chunk_indices:
        segment.vad_chunk_indices.remove(chunk.index)
    
    # Clear chunk assignment
    chunk.assigned_segment = None
    
    # Recalculate segment time boundaries from remaining chunks
    if segment.vad_chunk_indices:
        assigned_chunks = [c for c in all_chunks if c.index in segment.vad_chunk_indices]
        segment.start_time = min(c.start_time for c in assigned_chunks)
        segment.end_time = max(c.end_time for c in assigned_chunks)
    else:
        segment.start_time = None
        segment.end_time = None
    
    return segment, chunk

# %% ../../nbs/services/alignment.ipynb #74ed902b
def auto_align_sequential(
    segments: List[WorkingSegment],  # Segments to align
    chunks: List[VADChunk]  # VAD chunks to distribute
) -> tuple[List[WorkingSegment], List[VADChunk]]:  # Updated segments and chunks
    """Automatically align chunks to segments sequentially."""
    if not segments or not chunks:
        return segments, chunks
    
    # Simple proportional distribution based on text length
    total_text_len = sum(len(s.text) for s in segments)
    if total_text_len == 0:
        return segments, chunks
    
    chunk_idx = 0
    total_chunks = len(chunks)
    
    for segment in segments:
        # Calculate proportion of chunks for this segment
        proportion = len(segment.text) / total_text_len
        num_chunks = max(1, round(proportion * total_chunks))
        
        # Assign chunks to this segment
        end_idx = min(chunk_idx + num_chunks, total_chunks)
        for i in range(chunk_idx, end_idx):
            assign_chunk_to_segment(segment, chunks[i])
        
        chunk_idx = end_idx
        if chunk_idx >= total_chunks:
            break
    
    # Assign any remaining chunks to last segment
    if chunk_idx < total_chunks and segments:
        for i in range(chunk_idx, total_chunks):
            assign_chunk_to_segment(segments[-1], chunks[i])
    
    return segments, chunks

# %% ../../nbs/services/alignment.ipynb #649192f7
def get_unassigned_chunks(
    chunks: List[VADChunk]  # All VAD chunks
) -> List[VADChunk]:  # Chunks without segment assignments
    """Get all VAD chunks that are not assigned to any segment."""
    return [c for c in chunks if c.assigned_segment is None]

# %% ../../nbs/services/alignment.ipynb #5b3430f9
def get_segments_without_time(
    segments: List[WorkingSegment]  # All segments
) -> List[WorkingSegment]:  # Segments missing time alignment
    """Get all segments that don't have time alignment."""
    return [s for s in segments if s.start_time is None or s.end_time is None]
