"""Audio conversion service for browser-compatible CBR audio"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/services/audio_conversion.ipynb.

# %% auto #0
__all__ = ['DEBUG_AUDIO_CONVERSION', 'get_cache_path', 'needs_conversion', 'convert_to_cbr', 'ensure_cbr_audio']

# %% ../../nbs/services/audio_conversion.ipynb #audio-conv-imports
import subprocess
import hashlib
from pathlib import Path
from typing import Optional

# %% ../../nbs/services/audio_conversion.ipynb #audio-conv-debug
# Debug flag (set True for conversion tracing)
DEBUG_AUDIO_CONVERSION = True

# %% ../../nbs/services/audio_conversion.ipynb #audio-conv-cache-path
def get_cache_path(
    source_path: str,  # Path to the source audio file
    cache_dir: Path,  # Directory for cached files
) -> Path:  # Path where cached CBR file should be stored
    """Generate cache path for a converted audio file."""
    # Create hash from absolute path
    source_abs = Path(source_path).resolve()
    path_hash = hashlib.md5(str(source_abs).encode()).hexdigest()[:12]
    
    # Use original filename stem + hash for readability
    stem = source_abs.stem
    cache_name = f"{stem}_{path_hash}_cbr.mp3"
    # cache_name = f"{stem}_{path_hash}_cbr.wav"
    
    return cache_dir / cache_name

# %% ../../nbs/services/audio_conversion.ipynb #audio-conv-needs-conv
def needs_conversion(
    source_path: str,  # Path to the source audio file
    cache_path: Path,  # Path to the cached CBR file
) -> bool:  # True if conversion is needed
    """Check if audio needs conversion (cache missing or stale)."""
    if not cache_path.exists():
        if DEBUG_AUDIO_CONVERSION:
            print(f"[AUDIO_CONV] Cache miss: {cache_path}")
        return True
    
    # Check if source is newer than cache
    source_mtime = Path(source_path).stat().st_mtime
    cache_mtime = cache_path.stat().st_mtime
    
    if source_mtime > cache_mtime:
        if DEBUG_AUDIO_CONVERSION:
            print(f"[AUDIO_CONV] Cache stale: {cache_path}")
        return True
    
    if DEBUG_AUDIO_CONVERSION:
        print(f"[AUDIO_CONV] Cache hit: {cache_path}")
    return False

# %% ../../nbs/services/audio_conversion.ipynb #audio-conv-convert
def convert_to_cbr(
    source_path: str,  # Path to the source audio file
    output_path: Path,  # Path for the output CBR file
    bitrate: str = "192k",  # Target bitrate (e.g., "128k", "192k", "320k")
    sample_rate: int = 44100,  # Output sample rate in Hz
) -> bool:  # True if conversion succeeded
    """Convert audio file to CBR MP3 using ffmpeg."""
    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    cmd = [
        "ffmpeg",
        "-y",  # Overwrite output
        "-i", str(source_path),
        "-b:a", bitrate,  # Constant bitrate
        "-ar", str(sample_rate),  # Sample rate
        # "-ac", "2",  # Stereo
        str(output_path)
    ]
    
    if DEBUG_AUDIO_CONVERSION:
        print(f"[AUDIO_CONV] Running: {' '.join(cmd)}")
    
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True
        )
        if DEBUG_AUDIO_CONVERSION:
            print(f"[AUDIO_CONV] Conversion complete: {output_path}")
        return True
    except subprocess.CalledProcessError as e:
        if DEBUG_AUDIO_CONVERSION:
            print(f"[AUDIO_CONV] Conversion failed: {e.stderr}")
        return False
    except FileNotFoundError:
        if DEBUG_AUDIO_CONVERSION:
            print("[AUDIO_CONV] ffmpeg not found in PATH")
        return False

# %% ../../nbs/services/audio_conversion.ipynb #audio-conv-ensure
def ensure_cbr_audio(
    source_path: str,  # Path to the source audio file
    cache_dir: Optional[Path] = None,  # Cache directory (default: .cjm/data/audio_cache)
    project_root: Optional[Path] = None,  # Project root for default cache dir
) -> Optional[str]:  # Path to CBR audio file, or None if conversion failed
    """Ensure a CBR version of the audio file exists for browser playback."""
    source = Path(source_path)
    if not source.exists():
        if DEBUG_AUDIO_CONVERSION:
            print(f"[AUDIO_CONV] Source file not found: {source_path}")
        return None
    
    # Determine cache directory
    if cache_dir is None:
        if project_root is None:
            # Default to source file's directory
            cache_dir = source.parent / ".audio_cache"
        else:
            cache_dir = project_root / ".cjm" / "data" / "audio_cache"
    
    cache_path = get_cache_path(source_path, cache_dir)
    
    # Check if conversion needed
    if needs_conversion(source_path, cache_path):
        if DEBUG_AUDIO_CONVERSION:
            print(f"[AUDIO_CONV] Converting: {source_path}")
        
        if not convert_to_cbr(source_path, cache_path):
            # Conversion failed, fall back to original
            if DEBUG_AUDIO_CONVERSION:
                print(f"[AUDIO_CONV] Falling back to original: {source_path}")
            return source_path
    
    return str(cache_path)
