"""Display formatting utilities for dates, times, and filenames"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/services/formatting.ipynb.

# %% auto #0
__all__ = ['format_date', 'format_time', 'format_time_precise', 'format_audio_filename']

# %% ../../nbs/services/formatting.ipynb #fmt-imports
from typing import Optional
from datetime import datetime
from pathlib import Path

# %% ../../nbs/services/formatting.ipynb #fmt-format-date
def format_date(
    created_at: str  # ISO date string, Unix timestamp, or similar
) -> str:  # Formatted date for display
    """Format a date string for human-readable display (e.g., 'Jan 20, 2026')."""
    if not created_at:
        return "Unknown"
    
    # Try to parse as Unix timestamp first (float or int)
    try:
        timestamp = float(created_at)
        # Sanity check: timestamp should be reasonable (after year 2000, before year 2100)
        if 946684800 < timestamp < 4102444800:
            dt = datetime.fromtimestamp(timestamp)
            return dt.strftime("%b %d, %Y")  # e.g., "Jan 20, 2026"
    except (ValueError, TypeError, OSError):
        pass
    
    # Try to parse common ISO date formats
    date_formats = [
        "%Y-%m-%d %H:%M:%S.%f",  # SQLite with microseconds
        "%Y-%m-%d %H:%M:%S",     # SQLite without microseconds
        "%Y-%m-%dT%H:%M:%S.%f",  # ISO 8601 with microseconds
        "%Y-%m-%dT%H:%M:%S",     # ISO 8601 without microseconds
        "%Y-%m-%d",              # Date only
    ]
    
    for fmt in date_formats:
        try:
            dt = datetime.strptime(str(created_at).strip(), fmt)
            return dt.strftime("%b %d, %Y")  # e.g., "Jan 20, 2026"
        except ValueError:
            continue
    
    # Fallback: truncate if unparseable
    return str(created_at)[:16] if len(str(created_at)) > 16 else str(created_at)

# %% ../../nbs/services/formatting.ipynb #fmt-format-time
def format_time(
    seconds: Optional[float]  # Time in seconds
) -> str:  # Formatted time string (MM:SS)
    """Format seconds as MM:SS for display."""
    if seconds is None:
        return "--:--"
    minutes = int(seconds // 60)
    secs = int(seconds % 60)
    return f"{minutes:02d}:{secs:02d}"

def format_time_precise(
    seconds: Optional[float]  # Time in seconds
) -> str:  # Formatted time string (m:ss.s)
    """Format seconds as m:ss.s for sub-second display."""
    if seconds is None:
        return "-:--.-"
    minutes = int(seconds // 60)
    secs = seconds % 60
    return f"{minutes}:{secs:04.1f}"

# %% ../../nbs/services/formatting.ipynb #fmt-format-audio-filename
def format_audio_filename(
    audio_path: str  # Full path to audio file
) -> str:  # Shortened filename for display
    """Extract and format the filename from a path."""
    if not audio_path or audio_path == "Unknown":
        return "Unknown Source"
    return Path(audio_path).name
