"""Undo history management for segment editing workflows"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/services/history.ipynb.

# %% auto #0
__all__ = ['DEFAULT_MAX_HISTORY_DEPTH', 'push_history', 'pop_history']

# %% ../../nbs/services/history.ipynb #hist-imports
from typing import Optional, Tuple, List, Dict, Any

# %% ../../nbs/services/history.ipynb #hist-const
DEFAULT_MAX_HISTORY_DEPTH = 50

# %% ../../nbs/services/history.ipynb #hist-push
def push_history(
    history: List[Dict[str, Any]],  # Current history stack
    segments: List[Dict[str, Any]],  # Segments to snapshot
    focused_index: int,  # Focused index to snapshot
    max_depth: int = DEFAULT_MAX_HISTORY_DEPTH,  # Maximum history depth
) -> List[Dict[str, Any]]:  # Updated history stack
    """Push a state snapshot onto the history stack, enforcing max depth."""
    new_history = list(history)
    new_history.append({
        "segments": segments,
        "focused_index": focused_index,
    })
    if len(new_history) > max_depth:
        new_history = new_history[-max_depth:]
    return new_history

# %% ../../nbs/services/history.ipynb #hist-pop
def pop_history(
    history: List[Dict[str, Any]],  # Current history stack
) -> Optional[Tuple[List[Dict[str, Any]], int, List[Dict[str, Any]]]]:  # (segments, focused_index, updated_history) or None
    """Pop the most recent snapshot from the history stack, clamping the focused index."""
    if not history:
        return None
    
    new_history = list(history)
    previous_state = new_history.pop()
    segments = previous_state["segments"]
    focused_index = previous_state["focused_index"]
    
    # Clamp focus to valid range
    max_index = max(0, len(segments) - 1)
    focused_index = min(focused_index, max_index)
    
    return segments, focused_index, new_history
