"""Schema-knowledge helpers for presenting decomposition workflow sessions in a `cjm-fasthtml-workflow-session-management` session manager."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/workflow/session_integration.ipynb.

# %% auto #0
__all__ = ['DECOMP_STEP_TITLES', 'get_decomp_step_title', 'decomp_enricher', 'decomp_label_generator']

# %% ../../nbs/workflow/session_integration.ipynb #b2ef39f1
from pathlib import Path
from typing import Any, Dict

from cjm_workflow_state.state_store import SessionSummary
from cjm_fasthtml_workflow_session_management.utils import default_label

# %% ../../nbs/workflow/session_integration.ipynb #dc9645b3
DECOMP_STEP_TITLES:Dict[str, str] = {
    "selection": "Selection",
    "decomposition": "Segment & Align",
    "segmentation": "Segment & Align",  # alias for any state persisted under the old ID
    "review": "Review",
    "verify": "Verify",
}

def get_decomp_step_title(
    step_id:str # Raw step ID from the state store
) -> str: # Human-readable step title, or the raw ID if not mapped
    """Look up the human-readable title for a decomposition workflow step ID."""
    if not step_id:
        return ""
    return DECOMP_STEP_TITLES.get(step_id, step_id)

# %% ../../nbs/workflow/session_integration.ipynb #1a5e3a28
def decomp_enricher(
    state_json:Dict[str, Any] # Raw session state blob from the state store
) -> Dict[str, str]: # Display fields keyed by column name
    """Extract source count and segment count from decomposition workflow state."""
    step_states = state_json.get("step_states", {}) or {}
    
    selection_state = step_states.get("selection", {}) or {}
    sources = selection_state.get("selected_sources", []) or []
    
    # Segments may live under either key depending on when the state was persisted.
    seg_state = (
        step_states.get("segmentation", {})
        or step_states.get("decomposition", {})
        or {}
    )
    segments = seg_state.get("segments", []) or []
    
    return {
        "sources": str(len(sources)) if sources else "—",
        "segments": str(len(segments)) if segments else "—",
    }

# %% ../../nbs/workflow/session_integration.ipynb #a3f50eab
def decomp_label_generator(
    summary:SessionSummary, # Session metadata from the state store
    state_json:Dict[str, Any] # Raw session state blob
) -> str: # Resolved display label
    """Derive a default session label from the first selected source, or a timestamp."""
    step_states = state_json.get("step_states", {}) or {}
    selection_state = step_states.get("selection", {}) or {}
    sources = selection_state.get("selected_sources", []) or []
    
    if sources:
        first = sources[0] if isinstance(sources[0], dict) else {}
        record_id = first.get("record_id", "")
        if record_id:
            n = len(sources)
            if n == 1:
                return record_id
            return f"{record_id} (+{n - 1} more)"
    
    return default_label(summary.created_at)
