"""Main workflow class for structure decomposition"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/workflow/workflow.ipynb.

# %% auto #0
__all__ = ['StructureDecompWorkflow']

# %% ../../nbs/workflow/workflow.ipynb #604d9638
from typing import Dict, Any, List, Optional
from fasthtml.common import Div, P, A, APIRouter
from fastcore.basics import patch

from cjm_fasthtml_interactions.patterns.step_flow import Step, StepFlow
from cjm_fasthtml_interactions.core.context import InteractionContext
from cjm_fasthtml_interactions.patterns.async_loading import AsyncLoadingContainer
from cjm_fasthtml_interactions.core.state_store import get_session_id
from cjm_fasthtml_daisyui.components.actions.button import btn, btn_colors
from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui
from cjm_fasthtml_tailwind.utilities.spacing import m
from cjm_fasthtml_tailwind.core.base import combine_classes

from cjm_plugin_system.core.manager import PluginManager
from cjm_workflow_state.state_store import SQLiteWorkflowStateStore

from ..core.config import StructureDecompWorkflowConfig
from ..decomposition.models import DecompUrls
from ..alignment.models import AlignmentUrls
from cjm_fasthtml_card_stack.core.models import CardStackUrls
from ..selection.services.source import SourceService
from ..decomposition.services.segmentation import SegmentationService
from ..alignment.services.alignment import AlignmentService
from ..review.services.graph import GraphService

# Step renderers
from ..selection.components.step_renderer import render_selection_step
from ..combined.step_combined import render_combined_step
from ..review.components.step_renderer import render_review_step

# %% ../../nbs/workflow/workflow.ipynb #ngyugzueiw
class _SessionStateStoreAdapter:
    """Adapter bridging StepFlow's sess-based protocol to the pure session_id-based store."""
    
    def __init__(
        self,
        store: SQLiteWorkflowStateStore  # The pure, framework-agnostic store
    ):
        """Wrap a pure store with session resolution."""
        self._store = store
    
    def get_current_step(
        self,
        flow_id: str,  # Workflow identifier
        sess: Any  # FastHTML session object
    ) -> Optional[str]:  # Current step ID or None
        """Get current step ID, resolving session from sess."""
        return self._store.get_current_step(flow_id, get_session_id(sess))
    
    def set_current_step(
        self,
        flow_id: str,  # Workflow identifier
        sess: Any,  # FastHTML session object
        step_id: str  # Step ID to set as current
    ) -> None:
        """Set current step ID, resolving session from sess."""
        self._store.set_current_step(flow_id, get_session_id(sess), step_id)
    
    def get_state(
        self,
        flow_id: str,  # Workflow identifier
        sess: Any  # FastHTML session object
    ) -> Dict[str, Any]:  # Workflow state dictionary
        """Get all workflow state, resolving session from sess."""
        return self._store.get_state(flow_id, get_session_id(sess))
    
    def update_state(
        self,
        flow_id: str,  # Workflow identifier
        sess: Any,  # FastHTML session object
        updates: Dict[str, Any]  # State updates to apply
    ) -> None:
        """Update workflow state, resolving session from sess."""
        self._store.update_state(flow_id, get_session_id(sess), updates)
    
    def clear_state(
        self,
        flow_id: str,  # Workflow identifier
        sess: Any  # FastHTML session object
    ) -> None:
        """Clear all workflow state, resolving session from sess."""
        self._store.clear_state(flow_id, get_session_id(sess))

# %% ../../nbs/workflow/workflow.ipynb #2ac974ae
class StructureDecompWorkflow:
    """Self-contained structure decomposition workflow."""
    
    # Class-level metadata for discovery
    workflow_name: str = "structure_decomposition"
    workflow_version: str = "1.0.0"
    workflow_category: str = "ingestion"
    workflow_title: str = "Structure Decomposition"
    workflow_description: str = "Decompose transcripts into traversable context graph spines"
    
    def __init__(
        self,
        plugin_manager: PluginManager,  # Plugin manager from host application
        config: Optional[StructureDecompWorkflowConfig] = None  # Workflow configuration
    ):
        """Initialize the workflow with injected PluginManager."""
        self.config = config or StructureDecompWorkflowConfig()
        self._app = None  # Set in setup()
        
        # Store the injected PluginManager
        self._plugin_manager = plugin_manager
        
        # Create SQLite-backed state store for persistence (pure, session_id-based)
        self._state_store = SQLiteWorkflowStateStore(
            db_path=self.config.get_state_db_path()
        )
        
        # Adapter for StepFlow compatibility (resolves sess -> session_id)
        self._session_adapter = _SessionStateStoreAdapter(self._state_store)
        
        # Create services
        self._source_service = SourceService(
            plugin_manager,
            source_categories=self.config.source_categories
        )
        self._segmentation_service = SegmentationService(
            plugin_manager,
            plugin_name=self.config.text_plugin
        )
        self._alignment_service = AlignmentService(
            plugin_manager,
            plugin_name=self.config.vad_plugin
        )
        self._graph_service = GraphService(
            plugin_manager,
            plugin_name=self.config.graph_plugin
        )
        
        # Create StepFlow
        self._step_flow = self._create_step_flow()
        
        # Create routers (focused routers for each domain)
        self._routers = self._create_routers()
        self._stepflow_router = self._step_flow.create_router(
            prefix=self.config.get_full_stepflow_prefix()
        )
    
    @classmethod
    def create_and_setup(
        cls,
        app,  # FastHTML application instance
        plugin_manager: PluginManager,  # Plugin manager from host application
        config: Optional[StructureDecompWorkflowConfig] = None  # Workflow configuration
    ) -> "StructureDecompWorkflow":  # Configured and setup workflow instance
        """Create, configure, and setup a workflow in one call."""
        workflow = cls(plugin_manager=plugin_manager, config=config)
        workflow.setup(app)
        return workflow
    
    @property
    def plugin_manager(self) -> PluginManager:  # Plugin manager instance
        """Access to plugin manager."""
        return self._plugin_manager
    
    @property
    def source_service(self) -> SourceService:  # Source service instance
        """Access to source service."""
        return self._source_service
    
    @property
    def segmentation_service(self) -> SegmentationService:  # Segmentation service instance
        """Access to segmentation service."""
        return self._segmentation_service
    
    @property
    def alignment_service(self) -> AlignmentService:  # Alignment service instance
        """Access to alignment service."""
        return self._alignment_service
    
    @property
    def graph_service(self) -> GraphService:  # Graph service instance
        """Access to graph service."""
        return self._graph_service
    
    @property
    def state_store(self) -> SQLiteWorkflowStateStore:  # State store instance
        """Access to state store."""
        return self._state_store
    
    @property
    def routers(self) -> List[APIRouter]:  # List of workflow routers
        """Access to workflow routers (excludes stepflow router)."""
        return self._routers
    
    @property
    def stepflow_router(self) -> APIRouter:  # StepFlow-generated router
        """StepFlow-generated router."""
        return self._stepflow_router

# %% ../../nbs/workflow/workflow.ipynb #248d51b4
@patch
def setup(
    self: StructureDecompWorkflow,
    app  # FastHTML application instance
) -> None:
    """Initialize workflow with FastHTML app."""
    self._app = app

# %% ../../nbs/workflow/workflow.ipynb #4af8e3e9
@patch
def cleanup(
    self: StructureDecompWorkflow
) -> None:
    """Clean up workflow resources."""
    self._app = None

# %% ../../nbs/workflow/workflow.ipynb #12842405
@patch
def get_routers(
    self: StructureDecompWorkflow
) -> List[APIRouter]:  # List of routers to register
    """Return all routers for registration with the app."""
    return self._routers + [self._stepflow_router]

# %% ../../nbs/workflow/workflow.ipynb #5fbd6ae3
@patch
def render_entry_point(
    self: StructureDecompWorkflow,
    request,  # FastHTML request object
    sess  # FastHTML session object
):  # FastHTML component
    """Render the workflow entry point for embedding."""
    # Check if required plugins are available
    sources = self._source_service.get_available_sources()
    
    if not sources:
        # No source plugins available
        content = [
            P(
                "No transcription sources available. Please load transcription plugins first.",
                cls=combine_classes(text_dui.base_content.opacity(60), m.b(4))
            )
        ]
        if self.config.no_plugins_redirect:
            content.append(
                A(
                    "Go to Settings",
                    href=self.config.no_plugins_redirect,
                    cls=combine_classes(btn, btn_colors.primary)
                )
            )
        return Div(*content, id=self.config.container_id)
    
    # Sources available - load current status asynchronously
    current_status_url = self._core_routes["current_status"].to()
    return AsyncLoadingContainer(
        container_id=self.config.container_id,
        load_url=current_status_url
    )

# %% ../../nbs/workflow/workflow.ipynb #6306d3ee
@patch
def _create_step_flow(
    self: StructureDecompWorkflow
) -> StepFlow:  # Configured StepFlow instance
    """Create and configure the StepFlow instance."""
    workflow = self
    
    # Data loaders for each step
    def load_sources(request) -> Dict[str, Any]:
        """Load available transcription sources."""
        sources = workflow._source_service.get_available_sources()
        transcriptions = workflow._source_service.query_transcriptions(limit=50)
        return {"sources": sources, "transcriptions": transcriptions}
    
    def load_decomposition_data(request) -> Dict[str, Any]:
        """Load data for decomposition step."""
        # Data is loaded via init route, not data_loader
        return {}
    
    def load_review_data(request) -> Dict[str, Any]:
        """Load data for review step."""
        return {}
    
    # Validation functions
    def validate_selection(state: Dict[str, Any]) -> bool:
        """Validate that sources have been selected."""
        step_states = state.get("step_states", {})
        selection_state = step_states.get("selection", {})
        selected_sources = selection_state.get("selected_sources", [])
        return len(selected_sources) > 0
    
    def validate_decomposition(state: Dict[str, Any]) -> bool:
        """Validate that decomposition and alignment are complete (1:1)."""
        step_states = state.get("step_states", {})

        decomp_state = step_states.get("decomposition", {})
        segments = decomp_state.get("segments", [])

        alignment_state = step_states.get("alignment", {})
        vad_chunks = alignment_state.get("vad_chunks", [])

        # Must have segments, VAD chunks, and counts must match (1:1 alignment)
        return len(segments) > 0 and len(vad_chunks) > 0 and len(segments) == len(vad_chunks)
    
    def validate_review(state: Dict[str, Any]) -> bool:
        """Validate review step."""
        return True
    
    # Completion handler
    async def on_complete(state: Dict[str, Any], request):
        """Handle workflow completion - commit to graph."""
        # For placeholder, just return success message
        # Real implementation will call graph_service.commit_document()
        return Div(
            P("Workflow completed! Document committed to context graph."),
            id=workflow.config.container_id
        )
    
    # Create render wrapper for selection step that injects URLs
    def render_selection_step_with_urls(ctx: InteractionContext):
        """Render selection step with URL bundle from workflow."""
        return render_selection_step(
            ctx=ctx,
            urls=getattr(workflow, '_selection_urls', None),
        )
    
    # Create render wrapper for combined step that injects URL bundles
    def render_combined_step_with_urls(ctx: InteractionContext):
        """Render combined segment & align step with URL bundles from workflow."""
        return render_combined_step(
            ctx=ctx,
            decomp_urls=getattr(workflow, '_decomp_urls', DecompUrls()),
            align_urls=getattr(workflow, '_align_urls', AlignmentUrls()),
            switch_chrome_url=getattr(workflow, '_switch_chrome_url', ''),
        )
    
    return StepFlow(
        debug=True,
        flow_id=self.config.workflow_id,
        state_store=self._session_adapter,
        container_id=self.config.container_id,
        steps=[
            Step(
                id="selection",
                title="Select Sources",
                render=render_selection_step_with_urls,
                validate=validate_selection,
                data_loader=load_sources,
                data_keys=["selected_sources"],
                show_back=False,
                show_cancel=True,
                next_button_text="Continue"
            ),
            Step(
                id="decomposition",
                title="Segment & Align",
                render=render_combined_step_with_urls,
                validate=validate_decomposition,
                data_loader=load_decomposition_data,
                data_keys=["segments"],
                show_back=True,
                show_cancel=True,
                next_button_text="Continue"
            ),
            Step(
                id="review",
                title="Review",
                render=render_review_step,
                validate=validate_review,
                data_loader=load_review_data,
                data_keys=[],
                show_back=True,
                show_cancel=True,
                next_button_text="Commit to Graph"
            )
        ],
        on_complete=on_complete,
        show_progress=self.config.show_progress,
        wrap_in_form=True
    )

# %% ../../nbs/workflow/workflow.ipynb #a27c7fd5
@patch
def _create_routers(
    self: StructureDecompWorkflow
) -> List[APIRouter]:  # List of configured APIRouters
    """Create the workflow's API routers."""
    from cjm_fasthtml_workflow_transcript_decomp.routes.init import init_routers
    return init_routers(self)
