"""Placeholder step renderers for the structure decomposition workflow"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/steps.ipynb.

# %% auto #0
__all__ = ['render_selection_step', 'render_review_step']

# %% ../../nbs/components/steps.ipynb #483e14a6
from typing import Any

from fasthtml.common import Div, H2, P, Span
from cjm_fasthtml_interactions.core.context import InteractionContext
from cjm_fasthtml_daisyui.components.feedback.alert import alert, alert_colors
from cjm_fasthtml_tailwind.utilities.spacing import m
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_weight
from cjm_fasthtml_tailwind.core.base import combine_classes

from ..core.html_ids import StructureDecompHtmlIds

# %% ../../nbs/components/steps.ipynb #07cf9672
def render_selection_step(
    ctx: InteractionContext  # Interaction context with state and data
) -> Any:  # FastHTML component
    """Render Phase 1: Source Selection & Ordering step."""
    return Div(
        H2(
            "Phase 1: Source Selection & Ordering",
            cls=combine_classes(font_size._2xl, font_weight.bold, m.b(4))
        ),
        Div(
            Span("Placeholder", cls=str(font_weight.bold)),
            ": This step will allow selecting and ordering transcription sources.",
            cls=combine_classes(alert, alert_colors.info, m.b(4))
        ),
        P(
            "Features to implement:",
            cls=combine_classes(font_weight.semibold, m.b(2))
        ),
        Div(
            P("• Federated query across transcription plugin databases", cls=str(m.b(1))),
            P("• Multi-select source blocks from different plugins", cls=str(m.b(1))),
            P("• Drag-and-drop reordering for multi-chunk sources", cls=str(m.b(1))),
            P("• Preview of selected text blocks", cls=str(m.b(1))),
            cls=combine_classes(m.l(4), m.b(4))
        ),
        id=StructureDecompHtmlIds.SOURCE_SELECTOR
    )

# %% ../../nbs/components/steps.ipynb #41431031
def render_review_step(
    ctx:InteractionContext  # Interaction context with state and data
) -> Any:  # FastHTML component
    """Render Phase 3: Review & Commit step."""
    return Div(
        H2(
            "Phase 3: Review & Commit",
            cls=combine_classes(font_size._2xl, font_weight.bold, m.b(4))
        ),
        Div(
            Span("Placeholder", cls=str(font_weight.bold)),
            ": This step will provide the Reader View for final verification.",
            cls=combine_classes(alert, alert_colors.info, m.b(4))
        ),
        P(
            "Features to implement:",
            cls=combine_classes(font_weight.semibold, m.b(2))
        ),
        Div(
            P("• Linear document reader view", cls=str(m.b(1))),
            P("• Click-to-play audio for each segment", cls=str(m.b(1))),
            P("• Summary statistics (segment count, duration)", cls=str(m.b(1))),
            P("• Commit button to push to Context Graph", cls=str(m.b(1))),
            P("• Success/error feedback after commit", cls=str(m.b(1))),
            cls=combine_classes(m.l(4), m.b(4))
        ),
        id=StructureDecompHtmlIds.REVIEW_CONTAINER
    )
