"""Shared helper functions for the step_decomposition module"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/decomposition/components/helpers.ipynb.

# %% auto #0
__all__ = []

# %% ../../../nbs/decomposition/components/helpers.ipynb #c3d4e5f6
from typing import Any, Dict, List

from cjm_fasthtml_interactions.core.context import InteractionContext

from cjm_fasthtml_workflow_transcript_decomp.decomposition.models import (
    WorkingSegment, DecompositionStepState
)

# %% ../../../nbs/decomposition/components/helpers.ipynb #e5f6a7b8
def _get_decomposition_state(
    ctx: InteractionContext  # Interaction context with state
) -> DecompositionStepState:  # Typed decomposition step state
    """Get the full decomposition step state from context."""
    step_states = ctx.state.get("step_states", {})
    return step_states.get("decomposition", {})

# %% ../../../nbs/decomposition/components/helpers.ipynb #rvxle78vfj
def _get_segments(
    ctx: InteractionContext  # Interaction context with state
) -> List[WorkingSegment]:  # List of WorkingSegment objects
    """Get the list of segments from step state as WorkingSegment objects."""
    state = _get_decomposition_state(ctx)
    segment_dicts = state.get("segments", [])
    return [WorkingSegment.from_dict(s) for s in segment_dicts]

# %% ../../../nbs/decomposition/components/helpers.ipynb #2dliq35ph
def _is_initialized(
    ctx: InteractionContext  # Interaction context with state
) -> bool:  # True if segments have been initialized
    """Check if segments have been initialized."""
    state = _get_decomposition_state(ctx)
    return state.get("is_initialized", False)

# %% ../../../nbs/decomposition/components/helpers.ipynb #1zg9dsfg9za
def _get_visible_count(
    ctx: InteractionContext,  # Interaction context with state
    default: int = 3,  # Default visible card count
) -> int:  # Number of visible cards in viewport
    """Get the stored visible card count."""
    state = _get_decomposition_state(ctx)
    return state.get("visible_count", default)

# %% ../../../nbs/decomposition/components/helpers.ipynb #ev9120vz98m
def _get_card_width(
    ctx: InteractionContext,  # Interaction context with state
    default: int = 80,  # Default card width in rem
) -> int:  # Card stack width in rem
    """Get the stored card stack width."""
    state = _get_decomposition_state(ctx)
    return state.get("card_width", default)


#| export
def _get_is_auto_mode(
    ctx: InteractionContext,  # Interaction context with state
) -> bool:  # Whether card count is in auto-adjust mode
    """Get whether the card count is in auto-adjust mode."""
    state = _get_decomposition_state(ctx)
    return state.get("is_auto_mode", False)

# %% ../../../nbs/decomposition/components/helpers.ipynb #5qlapc1birw
def _get_history(
    ctx: InteractionContext  # Interaction context with state
) -> List[List[Dict[str, Any]]]:  # Stack of segment snapshots
    """Get the undo history stack."""
    state = _get_decomposition_state(ctx)
    return state.get("history", [])

# %% ../../../nbs/decomposition/components/helpers.ipynb #nnrf1g1wu5h
def _get_focused_index(
    ctx: InteractionContext  # Interaction context with state
) -> int:  # Currently focused segment index
    """Get the currently focused segment index."""
    state = _get_decomposition_state(ctx)
    return state.get("focused_index", 0)
