"""Router initialization for the structure decomposition workflow"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/init.ipynb.

# %% auto #0
__all__ = ['init_routers']

# %% ../../nbs/routes/init.ipynb #a996b93f
from typing import List

from fasthtml.common import APIRouter

# Import subpackage router assemblies
from .core.init import init_core_routers
from cjm_transcript_source_select.routes.init import init_selection_routers
from cjm_transcript_segmentation.routes.init import init_segmentation_routers
from cjm_transcript_vad_align.routes.init import init_alignment_routers
from cjm_transcript_review.routes.init import init_review_routers
from cjm_transcript_verify.routes.init import init_verify_routers

# Import from cjm-transcript-segment-align (extracted combined library)
from cjm_transcript_segment_align.components.handlers import (
    wrapped_seg_split, wrapped_seg_merge,
    wrapped_seg_undo, wrapped_seg_reset, wrapped_seg_ai_split,
    create_seg_init_chrome_wrapper, create_align_init_chrome_wrapper,
)
from cjm_transcript_segment_align.routes.chrome import init_chrome_router
from cjm_transcript_segment_align.routes.forced_alignment import init_forced_alignment_routers
from cjm_transcript_segment_align.services.forced_alignment import ForcedAlignmentService

from ..workflow.workflow import StructureDecompWorkflow

# %% ../../nbs/routes/init.ipynb #o055uobf0bp
def init_routers(
    workflow: "StructureDecompWorkflow",  # The workflow instance
) -> List[APIRouter]:  # List of configured routers
    """Initialize and return all workflow routers."""
    base_prefix = workflow.config.route_prefix

    # Initialize focused routers (status, sources, audio — chrome is now in segment-align lib)
    core_routers, core_routes = init_core_routers(
        workflow, f"{base_prefix}/core"
    )
    
    # Selection routers use dependency injection
    selection_routers, selection_urls, selection_routes, render_local_files_panel, sb_state = init_selection_routers(
        state_store=workflow.state_store,
        source_service=workflow.source_service,
        workflow_id=workflow.config.workflow_id,
        prefix=f"{base_prefix}/selection",
    )

    # Alignment routers (need to initialize first to get align_urls for seg init)
    # Create the align init wrapper first
    wrapped_align_init = create_align_init_chrome_wrapper()
    
    align_routers, align_urls, align_routes = init_alignment_routers(
        state_store=workflow.state_store,
        workflow_id=workflow.config.workflow_id,
        source_service=workflow.source_service,
        alignment_service=workflow.alignment_service,
        prefix=f"{base_prefix}/align",
        audio_src_url=core_routes["audio_src"].to(),
        wrapped_init=wrapped_align_init,
    )

    # Chrome switching router (from cjm-transcript-segment-align)
    chrome_router, chrome_routes = init_chrome_router(
        state_store=workflow.state_store,
        workflow_id=workflow.config.workflow_id,
        seg_urls=None,  # Will be set after seg routers init (forward reference)
        align_urls=align_urls,
        prefix=f"{base_prefix}/core/chrome",
    )
    switch_chrome_url = chrome_routes["switch_chrome"].to()

    # Forced alignment service (from cjm-transcript-segment-align)
    # Try to load the FA plugin if discovered but not yet loaded
    fa_service = ForcedAlignmentService(
        workflow.plugin_manager,
        workflow.config.fa_plugin_name,
    )
    fa_service.ensure_loaded()
    fa_is_available = fa_service.is_available()

    # Create the seg init wrapper with URLs needed for KB system + FA
    # (FA URLs will be set after FA router init — use forward reference pattern)
    fa_trigger_url = ""
    fa_toggle_url = ""

    wrapped_seg_init = create_seg_init_chrome_wrapper(
        align_urls=align_urls,
        switch_chrome_url=switch_chrome_url,
        fa_trigger_url=fa_trigger_url,
        fa_toggle_url=fa_toggle_url,
        fa_available=fa_is_available,
    )
    
    # Wrapped handlers for cross-domain coordination (alignment status OOB)
    seg_wrapped = {
        "init": wrapped_seg_init,
        "split": wrapped_seg_split,
        "merge": wrapped_seg_merge,
        "undo": wrapped_seg_undo,
        "reset": wrapped_seg_reset,
        "ai_split": wrapped_seg_ai_split,
    }
    
    # Segmentation routers use dependency injection
    seg_routers, seg_urls, seg_routes = init_segmentation_routers(
        state_store=workflow.state_store,
        workflow_id=workflow.config.workflow_id,
        source_service=workflow.source_service,
        segmentation_service=workflow.segmentation_service,
        prefix=f"{base_prefix}/seg",
        max_history_depth=workflow.config.max_history_depth,
        wrapped_handlers=seg_wrapped,
    )

    # Now initialize FA routes with seg_urls
    fa_routers = []
    if fa_is_available:
        fa_router, fa_routes = init_forced_alignment_routers(
            state_store=workflow.state_store,
            workflow_id=workflow.config.workflow_id,
            fa_service=fa_service,
            source_service=workflow.source_service,
            seg_urls=seg_urls,
            prefix=f"{base_prefix}/fa",
        )
        fa_routers = [fa_router]

        # Rebuild seg init wrapper with actual FA URLs
        fa_trigger_url = fa_routes["trigger"].to()
        fa_toggle_url = fa_routes["toggle"].to()

        wrapped_seg_init_with_fa = create_seg_init_chrome_wrapper(
            align_urls=align_urls,
            switch_chrome_url=switch_chrome_url,
            fa_trigger_url=fa_trigger_url,
            fa_toggle_url=fa_toggle_url,
            fa_available=True,
        )
        seg_wrapped["init"] = wrapped_seg_init_with_fa

        # Re-initialize segmentation routers with the updated init handler
        seg_routers, seg_urls, seg_routes = init_segmentation_routers(
            state_store=workflow.state_store,
            workflow_id=workflow.config.workflow_id,
            source_service=workflow.source_service,
            segmentation_service=workflow.segmentation_service,
            prefix=f"{base_prefix}/seg",
            max_history_depth=workflow.config.max_history_depth,
            wrapped_handlers=seg_wrapped,
        )

    # Update chrome router with seg_urls (forward reference resolution)
    chrome_router, chrome_routes = init_chrome_router(
        state_store=workflow.state_store,
        workflow_id=workflow.config.workflow_id,
        seg_urls=seg_urls,
        align_urls=align_urls,
        prefix=f"{base_prefix}/core/chrome",
    )

    # Review routers use dependency injection
    review_routers, review_urls, review_routes = init_review_routers(
        state_store=workflow.state_store,
        workflow_id=workflow.config.workflow_id,
        prefix=f"{base_prefix}/review",
        audio_src_url=core_routes["audio_src"].to(),
        graph_service=workflow.graph_service,
        alert_container_id="commit-alert-container",
    )
    
    # Verify routers use dependency injection
    verify_routers, verify_urls, verify_routes = init_verify_routers(
        state_store=workflow.state_store,
        workflow_id=workflow.config.workflow_id,
        prefix=f"{base_prefix}/verify",
        verify_service=workflow.verify_service,
    )

    # Store URL bundles on workflow for renderer access
    workflow._selection_urls = selection_urls
    workflow._seg_urls = seg_urls
    workflow._align_urls = align_urls
    workflow._review_urls = review_urls
    workflow._verify_urls = verify_urls
    workflow._switch_chrome_url = switch_chrome_url

    # Store selection-specific objects for renderer access
    workflow._render_local_files_panel = render_local_files_panel
    workflow._sb_state = sb_state

    # Store route dicts on workflow
    workflow._core_routes = core_routes
    workflow._selection_routes = selection_routes
    workflow._segmentation_routes = seg_routes
    workflow._alignment_routes = align_routes
    workflow._review_routes = review_routes
    workflow._verify_routes = verify_routes

    return (
        core_routers + [chrome_router] + fa_routers +
        selection_routers + seg_routers + align_routers +
        review_routers + verify_routers
    )
