"""URL bundle dataclasses for route handlers and UI renderers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/models.ipynb.

# %% auto #0
__all__ = ['AlignmentUrls']

# %% ../../nbs/routes/models.ipynb #rt-models-imports
from dataclasses import dataclass, field

from cjm_fasthtml_card_stack.core.models import CardStackUrls

# %% ../../nbs/routes/models.ipynb #rt-models-selection-urls
@dataclass
class AlignmentUrls:
    """URL bundle for Phase 2 alignment route handlers and renderers."""

    # Card stack navigation and viewport (from cjm-fasthtml-card-stack library)
    card_stack: CardStackUrls = field(default_factory=CardStackUrls)

    # Workflow-specific: initialization
    init: str = ""  # Initialize alignment (fetch VAD data)

    # Audio serving
    audio_src: str = ""  # Audio file serving URL base
