"""URL bundle dataclasses for route handlers and UI renderers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/routes/models.ipynb.

# %% auto #0
__all__ = ['DecompUrls', 'AlignmentUrls']

# %% ../../nbs/routes/models.ipynb #rt-models-imports
from dataclasses import dataclass, field

# %% ../../nbs/routes/models.ipynb #rt-models-decomp-urls
from cjm_fasthtml_card_stack.core.models import CardStackUrls


@dataclass
class DecompUrls:
    """URL bundle for Phase 2 decomposition route handlers and renderers."""

    # Card stack navigation and viewport (from cjm-fasthtml-card-stack library)
    card_stack: CardStackUrls = field(default_factory=CardStackUrls)

    # Workflow-specific: card operations
    split: str = ""  # Execute split at word position
    merge: str = ""  # Merge segment with previous
    enter_split: str = ""  # Enter split mode for focused segment
    exit_split: str = ""  # Exit split mode

    # Workflow-specific: toolbar
    reset: str = ""  # Reset to initial segments
    ai_split: str = ""  # AI (NLTK) re-split
    undo: str = ""  # Undo last operation

    # Workflow-specific: initialization
    init: str = ""  # Initialize segments from Phase 1

# %% ../../nbs/routes/models.ipynb #rt-models-selection-urls
@dataclass
class AlignmentUrls:
    """URL bundle for Phase 2 alignment route handlers and renderers."""

    # Card stack navigation and viewport (from cjm-fasthtml-card-stack library)
    card_stack: CardStackUrls = field(default_factory=CardStackUrls)

    # Workflow-specific: initialization
    init: str = ""  # Initialize alignment (fetch VAD data)

    # Audio serving
    audio_src: str = ""  # Audio file serving URL base
