"""Handler wrappers for cross-domain coordination (alignment status updates)"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/combined/handlers.ipynb.

# %% auto #0
__all__ = ['wrapped_seg_init', 'wrapped_seg_split', 'wrapped_seg_merge', 'wrapped_seg_undo', 'wrapped_seg_reset',
           'wrapped_seg_ai_split', 'wrapped_align_init', 'wrap_seg_mutation_handler', 'wrap_align_mutation_handler']

# %% ../../nbs/combined/handlers.ipynb #c3d4e5f6
import asyncio
from functools import wraps
from typing import Callable, Any

from cjm_fasthtml_interactions.core.state_store import get_session_id

from cjm_fasthtml_workflow_transcript_decomp.combined.step_combined import (
    render_alignment_status,
)
from cjm_fasthtml_workflow_transcript_decomp.decomposition.routes.handlers import (
    _handle_seg_init, _handle_seg_split, _handle_seg_merge,
    _handle_seg_undo, _handle_seg_reset, _handle_seg_ai_split,
)
from cjm_fasthtml_workflow_transcript_decomp.alignment.routes.handlers import (
    _handle_align_init,
)

# %% ../../nbs/combined/handlers.ipynb #e5f6a7b8
def wrap_seg_mutation_handler(
    handler:Callable,  # Handler function to wrap
) -> Callable:  # Wrapped handler that appends alignment status OOB
    """Wrap a segmentation mutation handler to add alignment status OOB."""
    @wraps(handler)
    async def wrapped(workflow, request, sess, *args, **kwargs):
        # Call the original handler (async or sync)
        if asyncio.iscoroutinefunction(handler):
            result = await handler(workflow, request, sess, *args, **kwargs)
        else:
            result = handler(workflow, request, sess, *args, **kwargs)
        
        # Get counts from state for alignment status
        session_id = get_session_id(sess)
        workflow_state = workflow.state_store.get_state(
            workflow.config.workflow_id, session_id
        )
        step_states = workflow_state.get("step_states", {})
        segment_count = len(step_states.get("segmentation", {}).get("segments", []))
        chunk_count = len(step_states.get("alignment", {}).get("vad_chunks", []))
        
        # Append alignment status OOB to result
        return (*result, render_alignment_status(segment_count, chunk_count, oob=True))
    
    return wrapped

# %% ../../nbs/combined/handlers.ipynb #f6a7b8c9
def wrap_align_mutation_handler(
    handler:Callable,  # Handler function to wrap
) -> Callable:  # Wrapped handler that appends alignment status OOB
    """Wrap an alignment mutation handler to add alignment status OOB."""
    @wraps(handler)
    async def wrapped(workflow, request, sess, *args, **kwargs):
        # Call the original handler (async or sync)
        if asyncio.iscoroutinefunction(handler):
            result = await handler(workflow, request, sess, *args, **kwargs)
        else:
            result = handler(workflow, request, sess, *args, **kwargs)
        
        # Get counts from state for alignment status
        session_id = get_session_id(sess)
        workflow_state = workflow.state_store.get_state(
            workflow.config.workflow_id, session_id
        )
        step_states = workflow_state.get("step_states", {})
        segment_count = len(step_states.get("segmentation", {}).get("segments", []))
        chunk_count = len(step_states.get("alignment", {}).get("vad_chunks", []))
        
        # Append alignment status OOB to result
        return (*result, render_alignment_status(segment_count, chunk_count, oob=True))
    
    return wrapped

# %% ../../nbs/combined/handlers.ipynb #b8c9d0e1
# Segmentation mutation handlers (change segment count)
wrapped_seg_init = wrap_seg_mutation_handler(_handle_seg_init)
wrapped_seg_split = wrap_seg_mutation_handler(_handle_seg_split)
wrapped_seg_merge = wrap_seg_mutation_handler(_handle_seg_merge)
wrapped_seg_undo = wrap_seg_mutation_handler(_handle_seg_undo)
wrapped_seg_reset = wrap_seg_mutation_handler(_handle_seg_reset)
wrapped_seg_ai_split = wrap_seg_mutation_handler(_handle_seg_ai_split)

# Alignment mutation handlers (change chunk count)
wrapped_align_init = wrap_align_mutation_handler(_handle_align_init)
