"""HTML ID constants for Phase 2 Shell: Dual-Column Layout shared chrome"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/combined/html_ids.ipynb.

# %% auto #0
__all__ = ['CombinedHtmlIds']

# %% ../../nbs/combined/html_ids.ipynb #c3d4e5f6
# Framework-agnostic — no external imports needed

class CombinedHtmlIds:
    """HTML ID constants for Phase 2 Shell: Dual-Column Layout shared chrome."""

    @staticmethod
    def as_selector(
        id_str:str  # The HTML ID to convert
    ) -> str:  # CSS selector with # prefix
        """Convert an ID to a CSS selector format."""
        return f"#{id_str}"

    # Shared Chrome
    SHARED_HINTS = "sd-shared-hints"
    SHARED_TOOLBAR = "sd-shared-toolbar"
    SHARED_CONTROLS = "sd-shared-controls"
    SHARED_FOOTER = "sd-shared-footer"
    ALIGNMENT_STATUS = "sd-alignment-status"

    # Decomposition Column
    DECOMP_COLUMN = "sd-decomp-column"
    DECOMP_COLUMN_HEADER = "sd-decomp-column-header"
    DECOMP_COLUMN_CONTENT = "sd-decomp-column-content"
    DECOMP_MINI_STATS = "sd-decomp-mini-stats"

    # Alignment Column
    ALIGNMENT_COLUMN = "sd-align-column"
    ALIGNMENT_COLUMN_HEADER = "sd-align-column-header"
    ALIGNMENT_COLUMN_CONTENT = "sd-align-column-content"
    ALIGNMENT_MINI_STATS = "sd-align-mini-stats"

    # State Tracking
    ACTIVE_COLUMN_INPUT = "sd-active-column"

    # Keyboard System (stable container)
    KEYBOARD_SYSTEM = "sd-keyboard-system"
