# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-fasthtml-workflow-transcript-decomp',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-fasthtml-workflow-transcript-decomp',
                'lib_path': 'cjm_fasthtml_workflow_transcript_decomp'},
  'syms': {}}
