"""State getters for the alignment step from InteractionContext"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/components/step_alignment/helpers.ipynb.

# %% auto #0
__all__ = []

# %% ../../../nbs/components/step_alignment/helpers.ipynb #align-hlp-exports
from typing import Any, Dict, List, Optional

from cjm_fasthtml_interactions.core.context import InteractionContext

from cjm_fasthtml_workflow_transcript_decomp.core.models import (
    VADChunk, AlignmentStepState
)

# %% ../../../nbs/components/step_alignment/helpers.ipynb #align-hlp-getters
def _get_alignment_state(
    ctx:InteractionContext  # Interaction context with state
) -> AlignmentStepState:  # Typed alignment step state
    """Get the full alignment step state from context."""
    step_states = ctx.state.get("step_states", {})
    return step_states.get("alignment", {})

def _get_vad_chunks(
    ctx:InteractionContext  # Interaction context with state
) -> List[VADChunk]:  # List of VADChunk objects
    """Get the list of VAD chunks from step state as VADChunk objects."""
    state = _get_alignment_state(ctx)
    chunk_dicts = state.get("vad_chunks", [])
    return [VADChunk.from_dict(c) for c in chunk_dicts]

def _is_alignment_initialized(
    ctx:InteractionContext  # Interaction context with state
) -> bool:  # True if VAD data has been fetched
    """Check if alignment has been initialized."""
    state = _get_alignment_state(ctx)
    return state.get("is_initialized", False)

def _get_focused_chunk_index(
    ctx:InteractionContext,  # Interaction context with state
    default:int=0,  # Default focused chunk index
) -> int:  # Currently focused VAD chunk index
    """Get the currently focused VAD chunk index."""
    state = _get_alignment_state(ctx)
    return state.get("focused_chunk_index", default)

def _get_alignment_visible_count(
    ctx:InteractionContext,  # Interaction context with state
    default:int=5,  # Default visible card count (compact cards)
) -> int:  # Number of visible cards in viewport
    """Get the stored visible card count."""
    state = _get_alignment_state(ctx)
    return state.get("visible_count", default)

def _get_alignment_card_width(
    ctx:InteractionContext,  # Interaction context with state
    default:int=40,  # Default card width in rem (narrower for alignment)
) -> int:  # Card stack width in rem
    """Get the stored card stack width."""
    state = _get_alignment_state(ctx)
    return state.get("card_width", default)

def _get_alignment_history(
    ctx:InteractionContext  # Interaction context with state
) -> list:  # Undo history stack
    """Get the undo history stack."""
    state = _get_alignment_state(ctx)
    return state.get("history", [])

def _get_media_path(
    ctx:InteractionContext  # Interaction context with state
) -> Optional[str]:  # Path to original audio file or None
    """Get the original audio file path."""
    state = _get_alignment_state(ctx)
    return state.get("media_path")

def _get_cbr_media_path(
    ctx:InteractionContext  # Interaction context with state
) -> Optional[str]:  # Path to CBR-converted audio or None
    """Get the CBR-converted audio file path for browser playback."""
    state = _get_alignment_state(ctx)
    return state.get("cbr_media_path")

def _get_playback_media_path(
    ctx:InteractionContext  # Interaction context with state
) -> Optional[str]:  # Path to audio for playback (CBR preferred, fallback to original)
    """Get the audio path for browser playback, preferring CBR version."""
    cbr_path = _get_cbr_media_path(ctx)
    if cbr_path:
        return cbr_path
    return _get_media_path(ctx)

def _get_audio_duration(
    ctx:InteractionContext  # Interaction context with state
) -> Optional[float]:  # Audio duration in seconds or None
    """Get the total audio duration."""
    state = _get_alignment_state(ctx)
    return state.get("audio_duration")
