"""Router assembly for Phase 2 decomposition routes"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/routes/decomposition/init.ipynb.

# %% auto #0
__all__ = ['init_decomposition_routers']

# %% ../../../nbs/routes/decomposition/init.ipynb #c3d4e5f6
from typing import List, Dict, Callable, Tuple

from fasthtml.common import APIRouter

from cjm_fasthtml_card_stack.core.models import CardStackUrls

from ..models import DecompUrls
from .card_stack import init_card_stack_router
from .handlers import init_workflow_router

from ...workflow.workflow import StructureDecompWorkflow

# %% ../../../nbs/routes/decomposition/init.ipynb #e5f6a7b8
def init_decomposition_routers(
    workflow: StructureDecompWorkflow,  # The workflow instance
    prefix: str,  # Base prefix for decomposition routes (e.g., "/workflow/decomp")
) -> Tuple[List[APIRouter], DecompUrls, Dict[str, Callable]]:  # (routers, urls, merged_routes)
    """Initialize and return all decomposition routers with URL bundle."""
    # Create empty URL bundle (populated after routes are defined)
    urls = DecompUrls()

    # Initialize focused routers
    card_stack_router, card_stack_routes = init_card_stack_router(
        workflow, f"{prefix}/card_stack", urls
    )
    workflow_router, workflow_routes = init_workflow_router(
        workflow, f"{prefix}/workflow", urls
    )

    # Populate the URL bundle using .to() on route functions
    urls.card_stack = CardStackUrls(
        nav_up=card_stack_routes["nav_up"].to(),
        nav_down=card_stack_routes["nav_down"].to(),
        nav_first=card_stack_routes["nav_first"].to(),
        nav_last=card_stack_routes["nav_last"].to(),
        nav_page_up=card_stack_routes["nav_page_up"].to(),
        nav_page_down=card_stack_routes["nav_page_down"].to(),
        update_viewport=card_stack_routes["update_viewport"].to(),
        save_width=card_stack_routes["save_width"].to(),
    )
    urls.enter_split = card_stack_routes["enter_split"].to()
    urls.exit_split = card_stack_routes["exit_split"].to()
    urls.init = workflow_routes["init"].to()
    urls.split = workflow_routes["split"].to()
    urls.merge = workflow_routes["merge"].to()
    urls.undo = workflow_routes["undo"].to()
    urls.reset = workflow_routes["reset"].to()
    urls.ai_split = workflow_routes["ai_split"].to()

    # Merge all routes for external access
    merged_routes = {
        **card_stack_routes,
        **workflow_routes,
    }

    routers = [card_stack_router, workflow_router]

    return routers, urls, merged_routes
