"""Configuration dataclass for structure decomposition workflow"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/config.ipynb.

# %% auto #0
__all__ = ['DEFAULT_WORKFLOW_CONFIG_DIR', 'StructureDecompWorkflowConfig']

# %% ../../nbs/core/config.ipynb #f614c39d
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional, List

# %% ../../nbs/core/config.ipynb #2a5c5d23
# Default config directory for workflow settings persistence
DEFAULT_WORKFLOW_CONFIG_DIR = Path("configs/workflows/structure_decomp")

# %% ../../nbs/core/config.ipynb #5831a299
@dataclass
class StructureDecompWorkflowConfig:
    """Configuration for structure decomposition workflow."""
    
    # Workflow identification
    workflow_id: str = "structure_decomposition"  # Unique identifier for this workflow
    
    # Route configuration
    route_prefix: str = "/structure_decomp"  # Base URL prefix for workflow routes
    stepflow_prefix: str = "/flow"  # Sub-prefix for StepFlow routes
    
    # Container ID for workflow content
    container_id: str = "sd-workflow-container"  # HTML ID for main workflow container
    
    # UI options
    show_progress: bool = True  # Show step progress indicator in StepFlow
    max_history_depth: int = 500  # Maximum undo history entries for decomposition phase
    
    # Plugin names (configurable to support different implementations)
    text_plugin: str = "cjm-text-plugin-nltk"  # Text processing plugin for sentence splitting
    vad_plugin: str = "cjm-media-plugin-silero-vad"  # VAD plugin for audio alignment
    graph_plugin: str = "cjm-graph-plugin-sqlite"  # Graph plugin for storage
    fa_plugin_name: str = "cjm-transcription-plugin-qwen3-forced-aligner"  # Forced alignment plugin (optional)
    
    # Plugin categories to discover for source data
    source_categories: List[str] = field(default_factory=lambda: ["transcription"])  # Categories for source plugins
    
    # Optional navigation URLs
    no_plugins_redirect: Optional[str] = None  # URL to redirect when required plugins unavailable
    
    # Database paths (for SQLite state store and federation)
    state_db_path: Optional[Path] = None  # Path to SQLite state database (uses default if None)
    
    # Configuration persistence
    config_dir: Path = field(default_factory=lambda: DEFAULT_WORKFLOW_CONFIG_DIR)  # Directory for workflow settings
    
    def get_full_stepflow_prefix(self) -> str:  # Combined route_prefix + stepflow_prefix
        """Get the full prefix for the StepFlow router."""
        return f"{self.route_prefix}{self.stepflow_prefix}"
    
    def get_state_db_path(self) -> Path:  # Resolved path to state database
        """Get the path to the SQLite state database."""
        if self.state_db_path:
            return self.state_db_path
        return self.config_dir / "workflow_state.db"
