"""Centralized HTML ID constants for structure decomposition workflow components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/html_ids.ipynb.

# %% auto #0
__all__ = ['StructureDecompHtmlIds']

# %% ../../nbs/core/html_ids.ipynb #e9b7aac8
# Framework-agnostic — no external imports needed

# %% ../../nbs/core/html_ids.ipynb #80854959
class StructureDecompHtmlIds:
    """HTML ID constants for structure decomposition workflow."""

    @staticmethod
    def as_selector(
        id_str:str  # The HTML ID to convert
    ) -> str:  # CSS selector with # prefix
        """Convert an ID to a CSS selector format."""
        return f"#{id_str}"

    # Workflow container (main wrapper for all workflow content)
    WORKFLOW_CONTAINER = "sd-workflow-container"

    # Step flow components
    STEP_CONTENT = "sd-step-content"
    STEP_PROGRESS = "sd-step-progress"

    # Phase 1: Selection & Ordering - Layout
    SOURCE_SELECTOR = "sd-source-selector"
    SOURCE_TABS = "sd-source-tabs"
    SOURCE_TAB_DB = "sd-source-tab-db"
    SOURCE_TAB_FILES = "sd-source-tab-files"
    SOURCE_TAB_CONTENT = "sd-source-tab-content"

    # Phase 1: Selection & Ordering - Browser Panel
    SOURCE_BROWSER = "sd-source-browser"
    SOURCE_LIST = "sd-source-list"
    SOURCE_FILTER_PLUGIN = "sd-source-filter-plugin"
    SOURCE_FILTER_SEARCH = "sd-source-filter-search"
    GROUPING_SELECTOR = "sd-grouping-selector"

    # Phase 1: Selection & Ordering - Queue Panel
    QUEUE_PANEL = "sd-queue-panel"
    QUEUE_CONTAINER = "sd-queue-container"
    QUEUE_LIST = "sd-queue-list"
    QUEUE_EMPTY = "sd-queue-empty"
    SOURCE_ORDER_LIST = "sd-source-order-list"
    SELECTED_SOURCES = "sd-selected-sources"

    # Phase 1: Selection & Ordering - Preview Panel
    PREVIEW_PANEL = "sd-preview-panel"
    PREVIEW_COLLAPSE = "sd-preview-collapse"
    PREVIEW_COLLAPSE_TOGGLE = "sd-preview-collapse-toggle"
    PREVIEW_CONTENT = "sd-preview-content"
    PREVIEW_HEADER = "sd-preview-header"
    PREVIEW_EMPTY = "sd-preview-empty"

    # Phase 1: Selection & Ordering - Keyboard Actions
    KB_ACTION_BUTTONS = "sd-kb-action-buttons"

    # Phase 1: Selection & Ordering - Local Files Browser
    LOCAL_FILES_BROWSER = "sd-local-files-browser"
    LOCAL_FILES_LIST = "sd-local-files-list"
    EXTERNAL_SOURCES_LIST = "sd-external-sources-list"

    # Phase 1: Selection & Ordering - Footer
    SELECTION_FOOTER = "sd-selection-footer"
    SELECTION_STATS = "sd-selection-stats"

    # Phase 2: Structural Decomposition - Main Layout
    # (Card stack IDs provided by CardStackHtmlIds from cjm-fasthtml-card-stack)
    # (Token selector IDs provided by TokenSelectorHtmlIds from cjm-fasthtml-token-selector)
    DECOMP_CONTAINER = "sd-decomp-container"
    DECOMP_HEADER = "sd-decomp-header"
    DECOMP_FOOTER = "sd-decomp-footer"
    DECOMP_STATS = "sd-decomp-stats"

    # Phase 2: Structural Decomposition - Toolbar
    # (Undo button ID is owned by the keyboard system — see SD_DECOMP_UNDO_BTN in keyboard_config)
    DECOMP_TOOLBAR = "sd-decomp-toolbar"
    DECOMP_RESET_BTN = "sd-decomp-reset-btn"
    DECOMP_AI_SPLIT_BTN = "sd-decomp-ai-split-btn"

    # Phase 2: Structural Decomposition - Split Mode
    SPLIT_MODE_CONTAINER = "sd-split-mode-container"
    SPLIT_MODE_ACTIONS = "sd-split-mode-actions"

    # Phase 2: Combined Segment & Align - Shared Chrome
    SHARED_HINTS = "sd-shared-hints"
    SHARED_TOOLBAR = "sd-shared-toolbar"
    SHARED_CONTROLS = "sd-shared-controls"
    SHARED_FOOTER = "sd-shared-footer"

    # Phase 2: Combined Segment & Align - Column Containers
    DECOMP_COLUMN = "sd-decomp-column"
    DECOMP_COLUMN_HEADER = "sd-decomp-column-header"
    DECOMP_MINI_STATS = "sd-decomp-mini-stats"
    ALIGNMENT_COLUMN = "sd-align-column"
    ALIGNMENT_COLUMN_HEADER = "sd-align-column-header"
    ALIGNMENT_MINI_STATS = "sd-align-mini-stats"

    # Phase 2: Combined Segment & Align - Active Column State
    ACTIVE_COLUMN_INPUT = "sd-active-column"

    # Phase 2: Temporal Alignment (sub-column IDs)
    ALIGNMENT_CONTAINER = "sd-alignment-container"
    TEXT_COLUMN = "sd-text-column"
    VAD_COLUMN = "sd-vad-column"
    AUDIO_PLAYER = "sd-audio-player"
    ACTIVE_SEGMENT = "sd-active-segment"

    # Phase 3: Review & Commit
    REVIEW_CONTAINER = "sd-review-container"
    READER_VIEW = "sd-reader-view"
    COMMIT_SUMMARY = "sd-commit-summary"

    # Common controls
    CANCEL_BTN = "sd-cancel-btn"
    SAVE_BTN = "sd-save-btn"
    COMMIT_BTN = "sd-commit-btn"

    # Settings
    SETTINGS_MODAL = "sd-settings-modal"
    SETTINGS_FORM = "sd-settings-form"
    SETTINGS_CONTAINER = "sd-settings-container"

    @staticmethod
    def _safe_id(
        value:str  # Raw value to sanitize for HTML ID use
    ) -> str:  # Sanitized string safe for HTML IDs
        """Sanitize a string for use in HTML IDs."""
        return value.replace(":", "-").replace("_", "-")

    @staticmethod
    def source_checkbox(
        record_id:str,  # Record identifier
        provider_id:str  # Provider identifier
    ) -> str:  # HTML ID for the source checkbox
        """Generate HTML ID for a source selection checkbox."""
        safe_rec = StructureDecompHtmlIds._safe_id(record_id)
        safe_prov = StructureDecompHtmlIds._safe_id(provider_id)
        return f"sd-source-cb-{safe_prov}-{safe_rec}"

    @staticmethod
    def source_row(
        record_id:str,  # Record identifier
        provider_id:str  # Provider identifier
    ) -> str:  # HTML ID for the source row
        """Generate HTML ID for a source browser row."""
        safe_rec = StructureDecompHtmlIds._safe_id(record_id)
        safe_prov = StructureDecompHtmlIds._safe_id(provider_id)
        return f"sd-source-row-{safe_prov}-{safe_rec}"

    @staticmethod
    def queue_item(
        record_id:str,  # Record identifier
        provider_id:str  # Provider identifier
    ) -> str:  # HTML ID for the queue item
        """Generate HTML ID for a queue item."""
        safe_rec = StructureDecompHtmlIds._safe_id(record_id)
        safe_prov = StructureDecompHtmlIds._safe_id(provider_id)
        return f"sd-queue-item-{safe_prov}-{safe_rec}"

    @staticmethod
    def segment_card(
        index:int  # Segment index in the decomposition
    ) -> str:  # HTML ID for the segment card
        """Generate HTML ID for a segment card."""
        return f"sd-segment-card-{index}"

    @staticmethod
    def vad_chunk(
        index:int  # VAD chunk index
    ) -> str:  # HTML ID for the VAD chunk element
        """Generate HTML ID for a VAD chunk element."""
        return f"sd-vad-chunk-{index}"
