"""Core HTML ID constants for workflow-level components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/html_ids.ipynb.

# %% auto #0
__all__ = ['CoreHtmlIds']

# %% ../../nbs/core/html_ids.ipynb #80854959
# Framework-agnostic — no external imports needed

class CoreHtmlIds:
    """HTML ID constants for workflow-level components.
    
    Page-specific IDs are in their respective packages:
    - selection.html_ids.SelectionHtmlIds
    - decomposition.html_ids.DecompositionHtmlIds
    - alignment.html_ids.AlignmentHtmlIds
    - combined.html_ids.CombinedHtmlIds
    - review.html_ids.ReviewHtmlIds
    """

    @staticmethod
    def as_selector(
        id_str:str  # The HTML ID to convert
    ) -> str:  # CSS selector with # prefix
        """Convert an ID to a CSS selector format."""
        return f"#{id_str}"

    # Workflow container (main wrapper for all workflow content)
    WORKFLOW_CONTAINER = "sd-workflow-container"

    # Step flow components
    STEP_CONTENT = "sd-step-content"
    STEP_PROGRESS = "sd-step-progress"

    # Common controls
    CANCEL_BTN = "sd-cancel-btn"
    SAVE_BTN = "sd-save-btn"
    COMMIT_BTN = "sd-commit-btn"

    # Settings
    SETTINGS_MODAL = "sd-settings-modal"
    SETTINGS_FORM = "sd-settings-form"
    SETTINGS_CONTAINER = "sd-settings-container"
